config/routes.rb
TwitterExtension::Engine.routes.draw do
  match 'settings' => 'settings#index'
  
  root :to => "settings#index"
end

app/models/anypresence_extension/account.rb
require AnypresenceExtension::Engine.root.join('app', 'models', 'anypresence_extension', 'account')

module AnypresenceExtension 
  class Account
    include ActiveModel::MassAssignmentSecurity
    include Mongoid::Document
    include Mongoid::Timestamps
    
    field :twitter_consumer_key, type: String
    field :twitter_consumer_secret, type: String
    field :twitter_oauth_token, type: String
    field :twitter_oauth_token_secret, type: String

  end
end

app/models/twitter_extension/account.rb
module TwitterExtension 
  class Account
    include ActiveModel::MassAssignmentSecurity
    include Mongoid::Document
    include Mongoid::Timestamps
    
    field :twitter_consumer_key, type: String
    field :twitter_consumer_secret, type: String
    field :twitter_oauth_token, type: String
    field :twitter_oauth_token_secret, type: String
    field :outgoing_message_format, type: String
    
    attr_accessible :twitter_consumer_key, :twitter_consumer_secret, :twitter_oauth_token, :twitter_oauth_token_secret, :outgoing_message_format

  end
end

app/controllers/twitter_extension/application_controller.rb
class TwitterExtension::ApplicationController < ApplicationController
  before_filter :authenticate_admin!
      
  layout 'layouts/admin'
end

app/controllers/twitter_extension/settings_controller.rb
require_dependency "twitter_extension/application_controller"

module TwitterExtension
  class SettingsController < ApplicationController
    
    def index;end
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweet_options_helper.rb
module TweetOptionsHelper
end

app/helpers/twitter_extension/application_helper.rb
module TwitterExtension
  module ApplicationHelper
  end
end

app/helpers/twitter_extension/settings_helper.rb
module TwitterExtension
  module SettingsHelper
  end
end

app/views/layouts/twitter_extension/application.html.haml
!!!
%html
  %head
    %title TwitterExtension
    = stylesheet_link_tag    "twitter_extension/application", :media => "all"
    = javascript_include_tag "twitter_extension/application"
    = stylesheet_link_tag 'admin'
    = csrf_meta_tags
  %body
    = yield

app/views/tweet_options/_form.html.haml
= simple_form_for [current_account, tweet_option] do |f|
  = f.error_messages
  %div.yui3-g
    %div.yui3-u-1-4
      = f.label :name
      %br
      = f.select :name, @available_objects
      %br
      %br
      %br
      = f.label :format
      %br
      = f.text_field :format, :size => 150
  %div.yui3-g
    %div.yui3-u-1-4
      = f.button :submit, "Submit!"

app/views/tweet_options/edit.html.haml
= link_to "Go back to settings", settings_path
%br
= render :partial => "form", :locals => { :tweet_option => @tweet_option }

app/views/tweet_options/index.html.haml
= link_to "Go back to settings", settings_path
%br
%br
- @tweet_options.each do |option|
  = link_to "#{option.name} - #{option.format}", [current_account, option]
  %br
%br
= link_to "Add new tweet option", new_account_tweet_option_path(@account)

app/views/tweet_options/new.html.haml
= link_to "Go back to settings", settings_path

%br
%br
= render :partial => "form", :locals => { :tweet_option => @tweet_option }

app/views/tweet_options/show.html.haml
= link_to "Go back to settings", settings_path
%br
%br
#tweet_option
  = @tweet_option.name
  \- #{@tweet_option.format}
%br
= link_to "Edit", edit_account_tweet_option_path(current_account, @tweet_option)
= link_to "Delete", [current_account, @tweet_option], :method => :delete, :confirm => "Are you sure you want to delete this tweet option?"

app/views/twitter_extension/settings/index.html.haml
%ul.breadcrumb
  %li
    = link_to 'Home', main_app.admin_root_path
    
  %li
    = link_to 'Extensions', main_app.admin_extensions_path
    
  %li.active Twitter

.page-header.text-muted
  %h1 Twitter
  %p The Twitter extension has no settings.